---
- name: Upload nginx.conf to EC2 instance
  ansible.builtin.copy:
    src: ../files/nginx.conf            # This is on my local control node
    dest: /tmp/nginx.conf          # Temporary path on the EC2 instance
- name: Copy a file into the container
  community.docker.docker_container_copy_into:
    container: nginx
    path: /tmp/nginx.conf
    container_path: /etc/nginx/conf.d/nginx.conf