volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/amrakibe/data/srcs_db
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/amrakibe/data/srcs_wp
      o: bind

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb_container
    restart: always
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
  wordpress:
    build: ./wordpress
    container_name: wordpress_container
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - mynetwork
  phpmyadmin:
    build: ./phpMyAdmin
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - 9090:90
    networks:
      - mynetwork
  nginx:
    container_name : nginx
    build: ./nginx
    volumes:
    - wp:/var/www/html
    depends_on:
    - wordpress
    ports:
    - 80:80
    - 443:443
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


