# create_droplet.yml
- name: Create Ubuntu Droplet on DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - digitalocean_token.yml

  tasks:
    - name: Create Droplet
      digital_ocean_droplet:
        state: present
        oauth_token: "{{ do_token }}"
        name: cloud-1
        region: sfo3
        size: s-1vcpu-1gb
        image: ubuntu-20-04-x64
        ssh_keys: [46662052]
        backups: no
        ipv6: yes
        monitoring: yes
        wait_timeout: 500
      register: droplet

    - name: Debug droplet structure
      debug:
        var: droplet
        verbosity: 0

    - name: Debug droplet IP address
      debug:
        msg: "{{  droplet.data.droplet.networks.v4[0].ip_address }}"

    - name: Add droplet to host group
      add_host:
        name: "{{  droplet.data.droplet.networks.v4[0].ip_address }}"
        groups: new_droplet

    - name: Wait for SSH to come up
      wait_for:
        host: "{{  droplet.data.droplet.networks.v4[0].ip_address }}"
        port: 22
        delay: 10
        timeout: 320
        state: started

    - name: Ensure [new_droplet] group exists
      lineinfile:
        path: ../inception-deploy/inventory/inventory.ini
        line: "[new_droplet]"
        create: yes
        insertafter: BOF
        state: present

    - name: Append new droplet IP to inventory.ini
      lineinfile:
        path: ../inception-deploy/inventory/inventory.ini
        line: "{{ droplet.data.droplet.networks.v4[0].ip_address }} ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa"
        create: yes
        insertafter: EOF
        state: present