- name: copy wordpress to remote server
  ansible.builtin.copy:
    src: ../../../srcs/requirements/wordpress
    dest: /home/ubuntu/inception/requirements
- name: Create data directory for wordpress
  file:
    path: "/home/data/wordpress"
    state: directory
  become: true